# Generated by Django 5.2.5 on 2025-08-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ret_1d', models.FloatField(null=True)),
                ('ret_5d', models.FloatField(null=True)),
                ('ma5_rel', models.FloatField(null=True)),
                ('ma20_rel', models.FloatField(null=True)),
                ('vol_5', models.FloatField(null=True)),
                ('sentiment_day', models.FloatField(default=0.0)),
                ('target_up', models.BooleanField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='market.instrument')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['instrument', 'date'], name='market_feat_instrum_43f097_idx')],
                'unique_together': {('instrument', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('published_at', models.DateTimeField()),
                ('sentiment', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='market.instrument')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['instrument', 'published_at'], name='market_news_instrum_f9957a_idx'), models.Index(fields=['published_at'], name='market_news_publish_515aa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceOHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=14)),
                ('high', models.DecimalField(decimal_places=6, max_digits=14)),
                ('low', models.DecimalField(decimal_places=6, max_digits=14)),
                ('close', models.DecimalField(decimal_places=6, max_digits=14)),
                ('volume', models.BigIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.instrument')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['instrument', 'date'], name='market_pric_instrum_88c656_idx')],
                'unique_together': {('instrument', 'date')},
            },
        ),
    ]
